#Write a Python program to perform various relational operations
a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b:"))
print("the value of A:",a)
print("the value of B:",b)
print("Result of a==b",a==b)
print("Result of a!=b",a!=b)
print("Result of a>b",a>b)
print("Result of a<b",a<b)
print("Result of a>=b",a>=b)
print("Result of a<=b",a<=b)
